/**
 * lib/economics.js
 * Data for the economic philosophies page (ekonomi.html).
 */

export const philosophies = [
  {
    id: 'planekonomi',
    label: 'Planekonomi',
    era: '1900-tal–',
    tagline: 'Samhällets resurser fördelas av en central plan, inte av priser.',
    category: 'stat',
    color: '#7a1f2a',
    pillars: [
      'Staten äger och kontrollerar produktionsmedlen',
      'Resurser allokeras via central planering',
      'Vinst ersätts av behovsstyrda produktionsmål',
      'Eliminerar privata marknader för kapitalvaror',
    ],
    stateSyn: 'Staten är den primära ekonomiska aktören och fastställer vad som ska produceras, hur och för vem. Planering kan ske centralt (Gosplan-modellen) eller i decentraliserade varianter med arbetarstyre.',
    fordelning: 'Fördelning sker politiskt snarare än via marknaden. Målet är likhet i utfall snarare än likhet i möjligheter.',
    kritik: 'Beräkningsproblemet (Mises, Hayek): utan prisinformation är det omöjligt att veta hur resurser värderas relativt varandra. Historisk erfarenhet visar på låg effektivitet, bristande innovation och frihetsförtryck.',
    tänkare: ['Karl Marx', 'Friedrich Engels', 'Nikolai Bukharin'],
    tensions: 'Beräkningsproblem, incitamentsproblem och politisk maktkoncentration. Centraliserad planering tenderar att prioritera sin egen fortlevnad framför folkliga behov.',
    axes: { marknad: 5, stat: 95, frihet: 10, jämlikhet: 80 },
    tableRow: { agande: 'Statligt/kollektivt', prisbildning: 'Centralt planerad', statRoll: 'Allomfattande', fordelning: 'Politiskt styrd' },
  },
  {
    id: 'marxism',
    label: 'Marxistisk ekonomi',
    era: '1800-tal–',
    tagline: 'Kapitalackumulation skapar systematisk exploatering av lönearbetare.',
    category: 'stat',
    color: '#9a2a2a',
    pillars: [
      'Mervärde — lönearbetare producerar mer värde än de erhåller',
      'Klassmotsättningar driver historisk förändring',
      'Kapital tenderar mot koncentration och kris',
      'Produktion för behov, inte profit',
    ],
    stateSyn: 'Staten är i kapitalismen ett instrument för den härskande klassen. I övergångsfasen till kommunism behöver proletariatet en egen stat — som på sikt ska bortdö.',
    fordelning: '"Från var och en efter förmåga, till var och en efter behov." Fördelning ska spegla behov, inte bidrag till marknaden.',
    kritik: 'Värdeteori baserad på arbete stämmer dåligt med hur priser faktiskt bildas. Historiska tillämpningar har konsekvent lett till auktoritärt styre snarare än frihetlig kommunism.',
    tänkare: ['Karl Marx', 'Friedrich Engels', 'Rosa Luxemburg', 'Antonio Gramsci'],
    tensions: 'Spänning mellan utopisk kommunism och faktisk statskapitalism. Vem definierar proletariatets intressen? Vad händer om "övergångsstaten" inte vill bortdö?',
    axes: { marknad: 10, stat: 85, frihet: 20, jämlikhet: 90 },
    tableRow: { agande: 'Gemensamt/kollektivt', prisbildning: 'Avskaffas i slutstadiet', statRoll: 'Övergångsinstrument', fordelning: 'Behovsstyrd' },
  },
  {
    id: 'keynesianism',
    label: 'Keynesianism',
    era: '1930-tal–',
    tagline: 'Efterfrågan driver ekonomin — och staten kan stabilisera den.',
    category: 'blandat',
    color: '#a04020',
    pillars: [
      'Aggregerad efterfrågan bestämmer produktion och sysselsättning',
      'Marknader kan fastna i jämvikt med hög arbetslöshet',
      'Finanspolitik som konjunkturverktyg',
      'Multiplikatoreffekten — statliga utgifter ger mer än vad de kostar',
    ],
    stateSyn: 'Staten bör aktivt stabilisera ekonomin genom att motverka konjunkturcykler. Underskott under lågkonjunktur, överskott under högkonjunktur.',
    fordelning: 'Fördelning är sekundär i det klassiska ramverket, men sociala investeringar motiveras som efterfrågestimulerande.',
    kritik: 'Riksekonomiska risker: politiken tenderar att bli asymmetrisk (underskott alltid, överskott aldrig). Crowding out — statliga lån konkurrerar med privata investeringar om kapital.',
    tänkare: ['John Maynard Keynes', 'Paul Samuelson', 'James Tobin', 'Paul Krugman'],
    tensions: 'Fungerar modellen på lång sikt? Keynes svarade: "På lång sikt är vi alla döda." Kritiker menar att kortsiktigt tänkande ackumulerar skuld och snedvridningar.',
    axes: { marknad: 50, stat: 60, frihet: 55, jämlikhet: 60 },
    tableRow: { agande: 'Blandat', prisbildning: 'Marknadsbaserad', statRoll: 'Konjunkturstabilisator', fordelning: 'Marknad + omfördelning' },
  },
  {
    id: 'blandekonomi',
    label: 'Blandekonomi',
    era: '1900-tal–',
    tagline: 'Marknadens effektivitet kombineras med statlig reglering och välfärd.',
    category: 'blandat',
    color: '#c9973a',
    pillars: [
      'Privat äganderätt kombineras med offentliga tjänster',
      'Staten korrigerar marknadsmisslyckanden',
      'Progressiv beskattning och sociala skyddsnät',
      'Reglering av monopol och externa effekter',
    ],
    stateSyn: 'Staten kompletterar marknaden snarare än ersätter den. Offentliga varor, marknadsmisslyckanden och omfördelning motiverar statlig inblandning.',
    fordelning: 'Marknaden fördelar primärt; staten omfördelar sekundärt via skatter och transfereringar. Mål om lika möjligheter snarare än lika utfall.',
    kritik: 'Gränsdragningsproblemet: var slutar nödvändig reglering och börjar kontraproduktiv intervention? Regulatorisk capture — regleringen tjänar branschens intressen snarare än samhällets.',
    tänkare: ['Paul Samuelson', 'John Kenneth Galbraith', 'Arthur Okun'],
    tensions: 'Inga tydliga principer för var gränsen ska dras. Pragmatism kan maskera inkohärens.',
    axes: { marknad: 65, stat: 55, frihet: 60, jämlikhet: 55 },
    tableRow: { agande: 'Privat + offentligt', prisbildning: 'Marknadsbaserad', statRoll: 'Korrektiv', fordelning: 'Marknad + omfördelning' },
  },
  {
    id: 'ordoliberalism',
    label: 'Ordoliberalism',
    era: '1930-tal–',
    tagline: 'Fri marknad förutsätter ett starkt rättsligt ramverk — konkurrens garanteras, inte lämnas åt sig själv.',
    category: 'marknad',
    color: '#8b3a2a',
    pillars: [
      'Marknadens spelregler sätts av starka, oberoende institutioner',
      'Konkurrens är ett mål som kräver aktiv upprätthållning',
      'Penningpolitisk stabilitet som konstitutionell princip',
      'Stat och marknad är komplementära, inte antagonister',
    ],
    stateSyn: 'Staten sätter spelplanen men väljer inte vinnare. Ordoliberalism är skeptisk till diskretionär politik och föredrar regelbaserade ramverk som begränsar politisk godtycklighet.',
    fordelning: 'Primärt via fungerande konkurrens och breda möjligheter. Marknadsinkomster ses som legitima när marknaden är genuint konkurrensutsatt. Socialpolitik kan vara förenlig om den inte snedvrider incitament.',
    kritik: 'Gränsdragning: var slutar ordningsramar och börjar interventionism? Kan anklagas för att vara för rigid och underuppskatta behovet av flexibel stabiliseringspolitik.',
    tänkare: ['Walter Eucken', 'Wilhelm Röpke', 'Alexander Rüstow', 'Ludwig Erhard'],
    tensions: 'Spänning mellan regelbaserat ramverk och demokratisk flexibilitet. Institutioner som ska vara oberoende kan bli oansvariga.',
    axes: { marknad: 80, stat: 45, frihet: 75, jämlikhet: 40 },
    tableRow: { agande: 'Privat', prisbildning: 'Konkurrensmarknaden', statRoll: 'Regelgivare/domare', fordelning: 'Konkurrens + selektiv socialpolitik' },
  },
  {
    id: 'neoklassicism',
    label: 'Neoklassisk ekonomi',
    era: '1870-tal–',
    tagline: 'Individer maximerar nytta, marknader tenderar mot jämvikt.',
    category: 'marknad',
    color: '#5a6e4a',
    pillars: [
      'Rationella aktörer med konsekventa preferenser',
      'Priser signalerar och allokerar resurser effektivt',
      'Marknader tenderar mot jämvikt vid störningar',
      'Marginalkostnaden bestämmer optimalt utbud',
    ],
    stateSyn: 'Staten bör begränsa sig till att korrigera tydliga marknadsmisslyckanden (externa effekter, offentliga varor, informationsasymmetrier). I övrigt är priset bättre informerat än byråkraten.',
    fordelning: 'Marknaden fördelar i enlighet med marginalproduktivitet. Omfördelning kan motiveras men distorsionskostnaden måste vägas in.',
    kritik: 'Rationalitetsantagandet är empiriskt felaktigt (beteendeekonomi). Modeller antar marknadsjämvikt men verkligheten präglas av instabilitet och boomen-bust-cykler.',
    tänkare: ['Alfred Marshall', 'Leon Walras', 'William Stanley Jevons', 'Gary Becker'],
    tensions: 'Abstraktion vs verklighet: modellerna är eleganta men riskerar att förväxla elegans med sanning. Tar inte tillräcklig hänsyn till makt, institutioner och historisk kontext.',
    axes: { marknad: 85, stat: 30, frihet: 80, jämlikhet: 30 },
    tableRow: { agande: 'Privat', prisbildning: 'Marknadsjämvikt', statRoll: 'Minimal/korrektiv', fordelning: 'Marginalproduktivitet' },
  },
  {
    id: 'austriansk',
    label: 'Österrikisk ekonomi',
    era: '1870-tal–',
    tagline: 'Kunskap är spridd och lokal — ingen central aktör kan aggregera den.',
    category: 'marknad',
    color: '#3f6f8f',
    pillars: [
      'Priset bär information som ingen central planering kan replikera',
      'Ekonomisk kalkyl är omöjlig utan äganderätt och priser',
      'Konjunkturcykler orsakas av kreditexpansion, inte marknadsfel',
      'Spontan ordning framgår av frivilliga utbyten',
    ],
    stateSyn: 'Staten kan inte känna till det som marknaden vet om preferenser och resurstillgång. Varje intervention snedvrider prisinformationen och skapar oavsiktliga konsekvenser.',
    fordelning: 'Frivillig, via marknaden. Omfördelning via statlig tvång ses som ett moraliskt och epistemiskt problem.',
    kritik: 'Praxeologi (deduktiv metod) ger svårkontrollerade prediktioner. Ignorerar maktasymmetrier och institutionell inbäddning av marknader.',
    tänkare: ['Ludwig von Mises', 'Friedrich Hayek', 'Murray Rothbard', 'Carl Menger'],
    tensions: 'Kan bli dogmatisk i sin marknadstro. Hayeks insikt om kunskap är djup, men slutsatsen att all intervention är kontraproduktiv är en överdrift som inte alltid följer av premisserna.',
    axes: { marknad: 95, stat: 10, frihet: 95, jämlikhet: 15 },
    tableRow: { agande: 'Strikt privat', prisbildning: 'Emergent prisinformation', statRoll: 'Rättsordning enbart', fordelning: 'Marknaden' },
  },
  {
    id: 'institutionell',
    label: 'Institutionell ekonomi',
    era: '1900-tal–',
    tagline: 'Ekonomin formas av institutioner, normer och makt — inte bara priser.',
    category: 'alternativ',
    color: '#4a5a6a',
    pillars: [
      'Institutioner (regler, normer, vanor) formar ekonomiskt beteende',
      'Makt och historia avgör marknadsutfall',
      'Teknologi och produktivkrafter driver strukturell förändring',
      'Ekonomin är inbäddad i social och kulturell kontext',
    ],
    stateSyn: 'Staten är inte en extern korrektör utan en del av de institutioner som formar marknaden. Statens utformning är avgörande för ekonomiska utfall.',
    fordelning: 'Fördelning formas av institutionell makt, inte enbart av priser och produktivitet. Ojämlikhet kan vara institutionellt reproducerad snarare än efficiensdriven.',
    kritik: 'Kan bli deskriptiv snarare än analytisk — förklarar hur saker är men ger svaga normativa riktlinjer. Risk för historisk determinism.',
    tänkare: ['Thorstein Veblen', 'John Kenneth Galbraith', 'Douglass North', 'Elinor Ostrom'],
    tensions: 'Hur förändras institutioner? Vem sätter spelreglerna för spelreglerna? Riskerar att ge cirkulära förklaringar.',
    axes: { marknad: 50, stat: 60, frihet: 50, jämlikhet: 55 },
    tableRow: { agande: 'Varierat', prisbildning: 'Institutionellt inbäddad', statRoll: 'Institutionsformare', fordelning: 'Makt + institutioner' },
  },
  {
    id: 'ekoekonomi',
    label: 'Ekologisk ekonomi',
    era: '1970-tal–',
    tagline: 'Ekonomin är ett delsystem av biosfären — inte tvärtom.',
    category: 'alternativ',
    color: '#4a7a4a',
    pillars: [
      'Planetära gränser sätter hårda villkor för ekonomisk aktivitet',
      'BNP-tillväxt är ett otillräckligt mål på lång sikt',
      'Externa effekter (utsläpp, biologisk mångfald) måste internaliseras',
      'Termodynamiska gränser begränsar evig tillväxt',
    ],
    stateSyn: 'Staten behöver sätta ett robust ramverk som prissätter naturkapital och sätter tak för resursuttag. Marknaden kan operera inom dessa gränser.',
    fordelning: 'Fördelning måste ta hänsyn till inter-generationell rättvisa — framtida generationer har anspråk på nutidens resursbeslut.',
    kritik: 'Teknologioptimister hävdar att grön tillväxt är möjlig — ekologisk ekonomi är för pessimistisk om teknologisk substitution. Svårt att operationalisera planetära gränser som politiska verktyg.',
    tänkare: ['Herman Daly', 'Nicholas Georgescu-Roegen', 'Kate Raworth', 'Tim Jackson'],
    tensions: 'Spänning mellan de-growth-förespråkare och reformister som tror på grön tillväxt. Vad händer med sysselsättning och välfärd i en nolltillväxtekonomi?',
    axes: { marknad: 40, stat: 65, frihet: 45, jämlikhet: 65 },
    tableRow: { agande: 'Blandat', prisbildning: 'Prissatt naturkapital', statRoll: 'Ekologisk ramgivare', fordelning: 'Inter-generationell rättvisa' },
  },
];
