/**
 * lib/ideologies.js
 * Data for the ideology library page.
 */

export const ideologies = [
  {
    id: 'liberalism',
    label: 'Klassisk liberalism',
    era: '1700-tal–',
    tagline: 'Individens frihet som samhällets grundval.',
    core: [
      'Individuell frihet och autonomi',
      'Begränsad stat och rättsstatsprincipen',
      'Fri marknad och privat äganderätt',
      'Universella mänskliga rättigheter',
    ],
    stateSyn: 'Staten ska skydda individuella rättigheter och upprätthålla rättsordningen — inte mer.',
    ekonomi: 'Frimarknadsekonomi med stark äganderätt. Omfördelning bör minimeras.',
    tänkare: ['John Locke', 'Adam Smith', 'John Stuart Mill'],
    spänningar: 'Spänning mellan negativ frihet och resurser som krävs för att utöva den.',
    color: '#5a6e4a',
  },
  {
    id: 'kommunism',
    label: 'Kommunism',
    era: '1800-tal–',
    tagline: 'Ett klasslöst samhälle där produktionsmedlen ägs gemensamt.',
    core: [
      'Avskaffande av privat äganderätt till produktionsmedlen',
      'Klasskampens centrala roll i historisk förändring',
      'Statens bortdöende som slutmål',
      'Från var och en efter förmåga, till var och en efter behov',
    ],
    stateSyn: 'Staten är i övergångsfasen ett instrument för proletariatets diktatur — ett temporärt verktyg som ska göra sig själv överflödigt.',
    ekonomi: 'Centralt planerad ekonomi med kollektivt ägande. Marknaden ersätts av planering utifrån samhälleliga behov snarare än profit.',
    tänkare: ['Karl Marx', 'Friedrich Engels', 'Vladimir Lenin'],
    spänningar: 'Spänning mellan det utopiska slutmålet — den statslösa kommunismen — och de historiska erfarenheterna av centraliserad makt och auktoritärt styre.',
    color: '#7a1f2a',
  },
  {
    id: 'socialliberalism',
    label: 'Socialliberalism',
    era: '1900-tal–',
    tagline: 'Frihet förutsätter verkliga möjligheter — inte bara formella rättigheter.',
    core: [
      'Individuell frihet kräver materiella förutsättningar',
      'Staten ska aktivt undanröja hinder för frihet',
      'Social rättvisa och lika möjligheter',
      'Universella rättigheter — civila, politiska och sociala',
    ],
    stateSyn: 'Staten är ett legitimt verktyg för att utjämna livsvillkor och garantera reell frihet. Offentliga institutioner, välfärd och reglering ses som förutsättningar — inte hot — för ett fritt samhälle.',
    ekonomi: 'Blandekonomi som kombinerar marknadens effektivitet med statlig omfördelning och reglering. Progressiv beskattning och sociala skyddsnät motiveras av frihetsprincipen.',
    tänkare: ['T.H. Green', 'L.T. Hobhouse', 'John Rawls', 'John Dewey'],
    spänningar: 'Var går gränsen för statlig intervention? Risken att omsorgen om frihet motiverar allt större statsmakt — och undergräver den individuella autonomi ideologin syftar till att skydda.',
    color: '#3f6f8f',
  },
  {
    id: 'socialdemokrati',
    label: 'Socialdemokrati',
    era: '1800-tal–',
    tagline: 'Marknadens kraft, statens omsorg.',
    core: [
      'Social trygghet och välfärdsstat',
      'Ekonomisk jämlikhet via omfördelning',
      'Reformism inom parlamentarisk ram',
      'Universella välfärdstjänster',
    ],
    stateSyn: 'Staten som aktiv korrektiv kraft mot marknadens ojämlikheter.',
    ekonomi: 'Blandekonomi. Stark offentlig sektor kombinerat med privat näringsliv.',
    tänkare: ['Eduard Bernstein', 'Gunnar Myrdal', 'Anthony Crosland'],
    spänningar: 'Spänning mellan ekonomisk effektivitet och jämlikhetsmål.',
    color: '#8b3a2a',
  },
  {
    id: 'konservatism',
    label: 'Konservatism',
    era: '1700-tal–',
    tagline: 'Ordning, tradition och organisk förändring.',
    core: [
      'Respekt för tradition och beprövade institutioner',
      'Organisk samhällsförändring',
      'Stark social sammanhållning',
      'Pragmatism framför ideologi',
    ],
    stateSyn: 'Staten som upprätthållare av ordning och tradition. Skeptisk till abstrakt reformism.',
    ekonomi: 'Marknadsvänlig men med utrymme för statliga ingrepp vid systemhot.',
    tänkare: ['Edmund Burke', 'Roger Scruton', 'Michael Oakeshott'],
    spänningar: 'Spänning mellan traditionsbevarande och ekonomisk liberalism (nyliberalism).',
    color: '#3a4a6e',
  },
  {
    id: 'nationalism',
    label: 'Nationalism',
    era: '1800-tal–',
    tagline: 'Nationen som politikens naturliga grund och gräns.',
    core: [
      'Nationell identitet som primär politisk gemenskap',
      'Folklig självbestämmanderätt och suveränitet',
      'Gemensamt språk, historia och kultur som sammanhållande kraft',
      'Staten och nationen bör sammanfalla',
    ],
    stateSyn: 'Staten är nationens politiska uttryck — dess uppgift är att skydda och bevara det nationella kollektivet, inte enbart individen.',
    ekonomi: 'Varierar brett — från protektionism och nationell industripolitik till marknadsekonomier med starka nationella intressen. Ekonomin är ett medel för nationell styrka, inte ett mål i sig.',
    tänkare: ['Johann Gottfried Herder', 'Giuseppe Mazzini', 'Ernest Renan'],
    spänningar: 'Spänning mellan medborgerlig nationalism — öppen för alla som delar värderingar — och etnisk nationalism, som definierar tillhörighet genom härkomst.',
    color: '#7a5a3a',
  },
  {
    id: 'nyliberalism',
    label: 'Nyliberalism',
    era: '1900-tal–',
    tagline: 'Marknadens frihet är grunden för både välstånd och personlig frihet.',
    core: [
      'Fri marknad och minimal statlig inblandning',
      'Privatisering och avreglering',
      'Individens ansvar för det egna utfallet',
      'Ekonomisk tillväxt som övergripande mål',
    ],
    stateSyn: 'Staten ska hålla sig tillbaka från ekonomin — dess roll är att upprätthålla spelreglerna, skydda äganderätten och säkra prisstabilitet. Välfärdsstaten ses som ineffektiv och hämmande för incitament.',
    ekonomi: 'Frimarknadsekonomi med låg skatt, begränsad omfördelning och tilltro till att konkurrens och prismekanismer allokerar resurser bättre än politiska beslut.',
    tänkare: ['Friedrich Hayek', 'Milton Friedman', 'James Buchanan', 'Ludwig von Mises'],
    spänningar: 'Spänning mellan marknadsfrihet och demokratisk legitimitet — avreglering och kapitalrörelser kan urholka nationalstatens förmåga att genomföra folkvalda politiska beslut.',
    color: '#2f7b7b',
  },
  {
    id: 'ordoliberalism',
    label: 'Ordoliberalism',
    era: '1900-tal–',
    tagline: 'Marknadens frihet kräver statens starka hand.',
    core: [
      'Fri konkurrens skyddad av rättsliga institutioner',
      'Stark stat med begränsat mandat — regelsättare, inte spelare',
      'Monopol och karteller aktivt motverkade',
      'Prisstabilitet och sunda statsfinanser som grundvillkor',
    ],
    stateSyn: 'Staten ska skapa och upprätthålla ramverket för marknaden — men aldrig ingripa direkt i prisbildning eller produktion.',
    ekonomi: 'Marknadsekonomi inom ett strikt institutionellt regelverk. Konkurrenslagstiftning prioriteras framför både laissez-faire och keynesiansk styrning.',
    tänkare: ['Walter Eucken', 'Wilhelm Röpke', 'Ludwig Erhard'],
    spänningar: 'Spänning mellan regelbaserad återhållsamhet och behovet av aktiva institutioner — vem vaktar väktarna?',
    color: '#5a6e9c',
  },
  {
    id: 'libertarianism',
    label: 'Libertarianism',
    era: '1900-tal–',
    tagline: 'Maximera frihet, minimera stat.',
    core: [
      'Icke-aggressionsprincipen',
      'Minimal eller ingen stat',
      'Absolut äganderätt',
      'Frivilliga associationer som samhällsgrund',
    ],
    stateSyn: 'Staten är i grunden illegitim. Minimal nattväktarstat i bästa fall.',
    ekonomi: 'Laissez-faire kapitalism. Skatter betraktas som tvång.',
    tänkare: ['Friedrich Hayek', 'Murray Rothbard', 'Robert Nozick'],
    spänningar: 'Hur hanteras kollektiva nyttigheter och negativa externaliteter utan stat?',
    color: '#c9973a',
  },
  {
    id: 'ekologism',
    label: 'Politisk ekologism',
    era: '1970-tal–',
    tagline: 'Planetens gränser som politikens fundament.',
    core: [
      'Ekologisk hållbarhet som överordnat mål',
      'Decentralisering och lokalsamhälle',
      'Gränsöverskridande solidaritet',
      'Icke-mänskliga varelsers intressen',
    ],
    stateSyn: 'Staten bör vara decentraliserad och underordnad ekologiska gränser.',
    ekonomi: 'Kritisk till tillväxtparadigmet. Förespråkar cirkulär och lokal ekonomi.',
    tänkare: ['Murray Bookchin', 'Carolyn Merchant', 'Hans Jonas'],
    spänningar: 'Spänning mellan demokratisk röstning och ekologiskt nödvändiga beslut.',
    color: '#4a7a4a',
  },
  {
    id: 'degrowth',
    label: 'Degrowth',
    era: '1970-tal–',
    tagline: 'Välstånd utan tillväxt — en annan ekonomis möjlighet.',
    core: [
      'Ekonomisk nedväxt som politiskt mål, inte kris att undvika',
      'Behov framför BNP — livskvalitet som måttstock',
      'Omfördelning av arbete, tid och resurser',
      'Lokala ekonomier och minskad konsumtion',
    ],
    stateSyn: 'Staten ska aktivt styra ned produktion och konsumtion samt omfördela resurser — men rörelsen är splittrad om statens roll kontra lokalt självstyre.',
    ekonomi: 'Post-tillväxtekonomi med fokus på omsorg, commons och ekologiska gränser. Ifrågasätter marknadslogikens dominans utan att nödvändigtvis förespråka central planering.',
    tänkare: ['Serge Latouche', 'Kate Raworth', 'Jason Hickel'],
    spänningar: 'Spänning mellan frivillig enkelhet och politisk tvångsreduktion — vems konsumtion ska minska, och vem bestämmer det?',
    color: '#5c7f56',
  },
  {
    id: 'kommunitarism',
    label: 'Kommunitarism',
    era: '1980-tal–',
    tagline: 'Gemenskapen formar individen — och bör skyddas.',
    core: [
      'Gemenskapens primat över individen',
      'Sociala band och kollektiv identitet',
      'Moraliska förpliktelser mot det gemensamma',
      'Kritik av atomistisk liberalism',
    ],
    stateSyn: 'Staten bör stödja och skydda livskraftiga gemenskaper.',
    ekonomi: 'Varierar — fokus på lokala institutioner och kooperativa strukturer.',
    tänkare: ['Alasdair MacIntyre', 'Michael Sandel', 'Charles Taylor'],
    spänningar: 'Risk för majoritetsförtryck av minoritetsgemenskaper.',
    color: '#6a4a7a',
  },
];
