/**
 * lib/ideologies.js
 * Data for the ideology library page.
 */

export const ideologies = [
  {
    id: 'liberalism',
    label: 'Klassisk liberalism',
    era: '1700-tal–',
    tagline: 'Individens frihet som samhällets grundval.',
    core: [
      'Individuell frihet och autonomi',
      'Begränsad stat och rättsstatsprincipen',
      'Fri marknad och privat äganderätt',
      'Universella mänskliga rättigheter',
    ],
    stateSyn: 'Staten ska skydda individuella rättigheter och upprätthålla rättsordningen — inte mer.',
    ekonomi: 'Frimarknadsekonomi med stark äganderätt. Omfördelning bör minimeras.',
    tänkare: ['John Locke', 'Adam Smith', 'John Stuart Mill'],
    spänningar: 'Spänning mellan negativ frihet och resurser som krävs för att utöva den.',
    color: '#5a6e4a',
  },
  {
    id: 'socialdemokrati',
    label: 'Socialdemokrati',
    era: '1800-tal–',
    tagline: 'Marknadens kraft, statens omsorg.',
    core: [
      'Social trygghet och välfärdsstat',
      'Ekonomisk jämlikhet via omfördelning',
      'Reformism inom parlamentarisk ram',
      'Universella välfärdstjänster',
    ],
    stateSyn: 'Staten som aktiv korrektiv kraft mot marknadens ojämlikheter.',
    ekonomi: 'Blandekonomi. Stark offentlig sektor kombinerat med privat näringsliv.',
    tänkare: ['Eduard Bernstein', 'Gunnar Myrdal', 'Anthony Crosland'],
    spänningar: 'Spänning mellan ekonomisk effektivitet och jämlikhetsmål.',
    color: '#8b3a2a',
  },
  {
    id: 'konservatism',
    label: 'Konservatism',
    era: '1700-tal–',
    tagline: 'Ordning, tradition och organisk förändring.',
    core: [
      'Respekt för tradition och beprövade institutioner',
      'Organisk samhällsförändring',
      'Stark social sammanhållning',
      'Pragmatism framför ideologi',
    ],
    stateSyn: 'Staten som upprätthållare av ordning och tradition. Skeptisk till abstrakt reformism.',
    ekonomi: 'Marknadsvänlig men med utrymme för statliga ingrepp vid systemhot.',
    tänkare: ['Edmund Burke', 'Roger Scruton', 'Michael Oakeshott'],
    spänningar: 'Spänning mellan traditionsbevarande och ekonomisk liberalism (nyliberalism).',
    color: '#3a4a6e',
  },
  {
    id: 'ordoliberalism',
    label: 'Ordoliberalism',
    era: '1900-tal–',
    tagline: 'Marknadens frihet kräver statens starka hand.',
    core: [
      'Fri konkurrens skyddad av rättsliga institutioner',
      'Stark stat med begränsat mandat — regelsättare, inte spelare',
      'Monopol och karteller aktivt motverkade',
      'Prisstabilitet och sunda statsfinanser som grundvillkor',
    ],
    stateSyn: 'Staten ska skapa och upprätthålla ramverket för marknaden — men aldrig ingripa direkt i prisbildning eller produktion.',
    ekonomi: 'Marknadsekonomi inom ett strikt institutionellt regelverk. Konkurrenslagstiftning prioriteras framför både laissez-faire och keynesiansk styrning.',
    tänkare: ['Walter Eucken', 'Wilhelm Röpke', 'Ludwig Erhard'],
    spänningar: 'Spänning mellan regelbaserad återhållsamhet och behovet av aktiva institutioner — vem vaktar väktarna?',
    color: '#5a6e9c',
  },
  {
    id: 'libertarianism',
    label: 'Libertarianism',
    era: '1900-tal–',
    tagline: 'Maximera frihet, minimera stat.',
    core: [
      'Icke-aggressionsprincipen',
      'Minimal eller ingen stat',
      'Absolut äganderätt',
      'Frivilliga associationer som samhällsgrund',
    ],
    stateSyn: 'Staten är i grunden illegitim. Minimal nattväktarstat i bästa fall.',
    ekonomi: 'Laissez-faire kapitalism. Skatter betraktas som tvång.',
    tänkare: ['Friedrich Hayek', 'Murray Rothbard', 'Robert Nozick'],
    spänningar: 'Hur hanteras kollektiva nyttigheter och negativa externaliteter utan stat?',
    color: '#c9973a',
  },
  {
    id: 'ekologism',
    label: 'Politisk ekologism',
    era: '1970-tal–',
    tagline: 'Planetens gränser som politikens fundament.',
    core: [
      'Ekologisk hållbarhet som överordnat mål',
      'Decentralisering och lokalsamhälle',
      'Gränsöverskridande solidaritet',
      'Icke-mänskliga varelsers intressen',
    ],
    stateSyn: 'Staten bör vara decentraliserad och underordnad ekologiska gränser.',
    ekonomi: 'Kritisk till tillväxtparadigmet. Förespråkar cirkulär och lokal ekonomi.',
    tänkare: ['Murray Bookchin', 'Carolyn Merchant', 'Hans Jonas'],
    spänningar: 'Spänning mellan demokratisk röstning och ekologiskt nödvändiga beslut.',
    color: '#4a7a4a',
  },
  {
    id: 'kommunitarism',
    label: 'Kommunitarism',
    era: '1980-tal–',
    tagline: 'Gemenskapen formar individen — och bör skyddas.',
    core: [
      'Gemenskapens primat över individen',
      'Sociala band och kollektiv identitet',
      'Moraliska förpliktelser mot det gemensamma',
      'Kritik av atomistisk liberalism',
    ],
    stateSyn: 'Staten bör stödja och skydda livskraftiga gemenskaper.',
    ekonomi: 'Varierar — fokus på lokala institutioner och kooperativa strukturer.',
    tänkare: ['Alasdair MacIntyre', 'Michael Sandel', 'Charles Taylor'],
    spänningar: 'Risk för majoritetsförtryck av minoritetsgemenskaper.',
    color: '#6a4a7a',
  },
];
