/**
 * lib/ideologies.js
 * Data for the ideology library page.
 */

export const ideologies = [
  {
    id: 'fascism',
    label: 'Fascism',
    era: '1900-tal–',
    tagline: 'Staten och nationen överordnas individen.',
    core: [
      'Staten betraktas som en organisk helhet där individen underordnas helheten.',
      'Betonar auktoritärt ledarskap och stark central makt',
      'Radikal nationalism och mobilisering av massan',
      'Avvisar både liberalism och marxism',
    ],
    stateSyn: 'Staten ses som den högsta politiska och moraliska enheten, med uppgift att skapa enhet, styrka och sammanhållning inom nationen. Individens rättigheter underordnas kollektivet och statens mål. Demokratiska institutioner ersätts ofta av centraliserad maktutövning, där ledarskap och lydnad betonas framför pluralism och maktdelning.',
    ekonomi: 'Statligt styrd — varken fri marknad eller planekonomi i klassisk mening. Privat ägande kan tillåtas, men underställs statens intressen. Ekonomin organiseras ofta i korporativa strukturer där staten samordnar relationen mellan arbetsgivare, arbetstagare och andra samhällsgrupper. Ekonomisk politik syftar främst till nationell styrka, självförsörjning och stabilitet.',
    tänkare: ['Benito Mussolini', 'Giovanni Gentile'],
    spänningar: 'Spänning mellan total statlig kontroll och behovet av ekonomisk effektivitet. Även motsättningar mellan olika former av nationalism, från statligt centrerade till mer exkluderande och identitetsbaserade varianter. Samtidigt begränsar betoningen på enhet och lydnad utrymmet för intern pluralism och idéutveckling.',
    color: '#6b4c2a',
  },
  {
    id: 'liberalism',
    label: 'Klassisk liberalism',
    era: '1700-tal–',
    tagline: 'Individens frihet som samhällets grundval.',
    core: [
      'Individuell frihet och autonomi',
      'Begränsad stat och rättsstatsprincipen',
      'Fri marknad och privat äganderätt',
      'Universella mänskliga rättigheter',
    ],
    stateSyn: 'Staten ska i första hand skydda individuella rättigheter och upprätthålla rättsordningen. Dess legitimitet vilar på att den skyddar medborgarna från godtycke, inte på att den formar deras liv eller värderingar. Klassiska liberaler betonar därför en begränsad stat med tydligt definierade kärnfunktioner, även om vissa företrädare har accepterat viss offentlig verksamhet, exempelvis inom utbildning eller infrastruktur.',
    ekonomi: 'Marknadsekonomi med stark äganderätt och frivilligt utbyte som norm. Omfördelning bör i regel begränsas, eftersom välstånd anses skapas bäst när individer kan disponera sin egendom och bära konsekvenserna av sina beslut. Samtidigt har det inom den klassiskt liberala traditionen funnits oenighet om hur långt staten får gå för att upprätthålla konkurrens, utbildning och social stabilitet.',
    tänkare: ['John Locke', 'Adam Smith', 'John Stuart Mill'],
    spänningar: 'Spänning mellan negativ frihet — frånvaron av tvång — och de reella resurser som krävs för att utöva den. En person utan tillgångar är formellt fri men faktiskt begränsad. Klassiska liberaler är oense om huruvida detta är statens ansvar att åtgärda, eller om det räcker att undanröja rättsliga hinder.',
    color: '#5a6e4a',
  },
  {
    id: 'kommunism',
    label: 'Kommunism',
    era: '1800-tal–',
    tagline: 'Ett klasslöst samhälle där produktionsmedlen ägs gemensamt.',
    core: [
      'Avskaffande av privat äganderätt till produktionsmedlen',
      'Klasskampens centrala roll i historisk förändring',
      'Statens bortdöende som slutmål',
      'Från var och en efter förmåga, till var och en efter behov',
    ],
    stateSyn: 'I klassisk marxistisk teori är staten i övergångsfasen ett instrument för proletariatets herravälde — ett temporärt verktyg som på sikt ska göra sig självt överflödigt. När klassmotsättningarna är upplösta och ett klasslöst samhälle uppnåtts ska staten bortdö och ersättas av fri association mellan individer och kollektiv.',
    ekonomi: 'Kommunismen syftar till gemensamt ägande av produktionsmedlen och till att marknadens logik ska ersättas av produktion för behov snarare än profit. I historiska tillämpningar har detta ofta tagit formen av central planering, även om den marxistiska teorin inte alltid specificerar en enda exakt ekonomisk modell för det framtida kommunistiska samhället. Kapitalackumulation och exploatering av lönearbete ses som grundläggande orättvisor som måste avskaffas, inte enbart reformeras.',
    tänkare: ['Karl Marx', 'Friedrich Engels', 'Vladimir Lenin'],
    spänningar: 'Spänning mellan det utopiska slutmålet — den statslösa kommunismen — och de historiska erfarenheterna av centraliserad makt och auktoritärt styre. Hur ska övergångsfasen styras utan att makten stelnar? Och vem har rätt att definiera proletariatets intressen i dess namn?',
    color: '#7a1f2a',
  },
  {
    id: 'socialliberalism',
    label: 'Socialliberalism',
    era: '1900-tal–',
    tagline: 'Frihet förutsätter verkliga möjligheter — inte bara formella rättigheter.',
    core: [
      'Individuell frihet kräver materiella och sociala förutsättningar',
      'Staten kan legitimt undanröja hinder för frihet',
      'Social rättvisa och lika möjligheter',
      'Universella rättigheter — civila, politiska och sociala',
    ],
    stateSyn: 'Staten ses som ett legitimt verktyg för att utjämna livsvillkor och stärka människors reella frihet. Offentliga institutioner, välfärd och reglering betraktas därför ofta som förutsättningar — inte nödvändigtvis hot — för ett fritt samhälle. En stat som enbart skyddar formella rättigheter utan att beakta de materiella villkoren för att utöva dem anses otillräcklig.',
    ekonomi: 'Blandekonomi som kombinerar marknadens effektivitet med statlig omfördelning och reglering. Progressiv beskattning och sociala skyddsnät motiveras av frihetsprincipen snarare än enbart solidaritet — den som saknar utbildning, hälsa eller grundläggande trygghet kan inte utöva sin frihet på lika villkor som den som har det. Traditionen spänner från tidiga socialliberaler till moderna rättviseteorier inom den liberala familjen.',
    tänkare: ['T.H. Green', 'L.T. Hobhouse', 'John Rawls', 'John Dewey'],
    spänningar: 'Var går gränsen för statlig intervention? Risken är att omsorgen om frihet motiverar en allt större statsmakt — och därmed undergräver den individuella autonomi ideologin syftar till att skydda. Dessutom finns en spänning mot klassisk liberalism om vad frihet egentligen betyder: är avsaknad av tvång tillräckligt, eller krävs reella möjligheter?',
    color: '#3f6f8f',
  },
  {
    id: 'socialdemokrati',
    label: 'Socialdemokrati',
    era: '1800-tal–',
    tagline: 'Marknadens kraft, statens omsorg.',
    core: [
      'Social trygghet och välfärdsstat',
      'Ekonomisk jämlikhet via omfördelning',
      'Reformism inom parlamentarisk ram',
      'Universella välfärdstjänster',
    ],
    stateSyn: 'Staten är en aktiv korrektiv kraft mot marknadens ojämlikheter — inte ett nödvändigt ont utan ett demokratiskt verktyg. Genom lagstiftning, skatter och offentliga institutioner kan politiken forma de villkor under vilka marknaden verkar och säkra att dess frukter fördelas brett.',
    ekonomi: 'Blandekonomi med stark offentlig sektor kombinerad med privat näringsliv. Marknaden accepteras i regel som ett effektivt sätt att producera varor och tjänster, men lämnas inte oreglerad. Omfördelning via progressiv beskattning och universella välfärdstjänster är central. Socialdemokratin har utvecklats från socialistiska rötter till en reformistisk mittenposition i många länder, med betydande variation mellan exempelvis nordiska och kontinentaleuropeiska traditioner.',
    tänkare: ['Eduard Bernstein', 'Gunnar Myrdal', 'Anthony Crosland'],
    spänningar: 'Spänning mellan ekonomisk effektivitet och jämlikhetsmål — höga skatter och generösa ersättningssystem kan enligt kritiker dämpa incitament och konkurrenskraft. Dessutom finns en långsiktig ideologisk spänning: är socialdemokratin ett steg mot socialism, eller är den i grunden ett försvar för en reglerad kapitalism?',
    color: '#8b3a2a',
  },
  {
    id: 'konservatism',
    label: 'Konservatism',
    era: '1700-tal–',
    tagline: 'Ordning, tradition och organisk förändring.',
    core: [
      'Respekt för tradition och beprövade institutioner',
      'Organisk samhällsförändring',
      'Stark social sammanhållning',
      'Skepsis mot abstrakt ideologi och preferens för praktisk erfarenhet',
    ],
    stateSyn: 'Staten ses som upprätthållare av ordning, kontinuitet och de institutioner som generationer byggt upp. Den bör vara skeptisk till abstrakt reformism och snabba systemförändringar — inte av tröghet, utan av insikten att komplexa samhällen rymmer mer erfarenhetsburen kunskap än någon enskild generation helt kan överblicka.',
    ekonomi: 'Marknadsvänlig men utan stark ekonomisk dogmatism. Utrymme finns för statliga ingrepp vid systemhot, social upplösning eller när marknaden underminerar de gemenskaper och traditioner som bär samhällets moraliska infrastruktur. Stabilitet och institutionell kontinuitet värderas ofta lika högt som effektivitet.',
    tänkare: ['Edmund Burke', 'Roger Scruton', 'Michael Oakeshott'],
    spänningar: 'Spänning mellan traditionsbevarande och ekonomisk liberalism — marknadsomvandling kan i praktiken slita sönder de gemenskaper och strukturer som konservatismen vill bevara. Frågan blir då vad konservatismen egentligen ska bevara när ekonomin förändrar samhället snabbare än traditionerna hinner anpassas.',
    color: '#3a4a6e',
  },
  {
    id: 'nationalism',
    label: 'Nationalism',
    era: '1800-tal–',
    tagline: 'Nationen som politikens naturliga grund och gräns.',
    core: [
      'Nationell identitet som primär politisk gemenskap',
      'Folklig självbestämmanderätt och suveränitet',
      'Gemensamt språk, historia och kultur som sammanhållande kraft',
      'Staten och nationen bör i någon mening sammanfalla',
    ],
    stateSyn: 'Staten förstås som nationens politiska uttryck — dess uppgift är att skydda och bevara det nationella kollektivet, inte enbart individen. Legitimitet kan i nationalistiskt tänkande vila på historisk och kulturell gemenskap snarare än enbart universella principer. En stat som förlorar sin nationella förankring riskerar, i denna syn, att bli ett administrativt skal utan folklig grund. I vissa varianter betonas även statens roll i att aktivt stärka social sammanhållning, kulturell kontinuitet och nationell identitet.',
    ekonomi: 'Varierar brett — från protektionism och nationell industripolitik till marknadsekonomier med starka nationella intressen. Ekonomin är ett medel för nationell styrka och sammanhållning, inte ett mål i sig. Frihandel accepteras ofta när den anses gynna nationen, men ifrågasätts när den uppfattas underordna nationella intressen globala marknadslogiker.',
    tänkare: ['Johann Gottfried Herder', 'Giuseppe Mazzini', 'Ernest Renan'],
    spänningar: 'Spänning mellan medborgerlig nationalism — öppen för alla som delar värderingar och lojalitet — och etnisk nationalism, som definierar tillhörighet genom härkomst. Dessutom finns en spänning mellan mer liberala former av nationalism och mer konservativa varianter, där nationell gemenskap kopplas tydligare till kultur, tradition och social ordning (ibland benämnt nationalkonservatism). Hur hanteras minoriteter inom nationen, och hur definieras gränsen för vem som hör till?',
    color: '#7a5a3a',
  },
  {
    id: 'nyliberalism',
    label: 'Nyliberalism',
    era: '1900-tal–',
    tagline: 'Marknadens frihet ses som central för både välstånd och individuell autonomi.',
    core: [
      'Fri marknad och begränsad statlig ekonomisk styrning',
      'Privatisering och avreglering',
      'Individens ansvar för det egna utfallet',
      'Effektiv resursallokering via marknader',
    ],
    stateSyn: 'Staten bör i huvudsak upprätthålla spelreglerna, skydda äganderätten och säkra stabila institutionella villkor, snarare än att styra priser, produktion eller resursfördelning direkt. Välfärdsstaten ses ofta som ineffektiv om den blir alltför omfattande eller snedvrider incitament. Samtidigt förutsätter nyliberala modeller normalt en aktiv stat som konstruerar och försvarar marknadsordningen.',
    ekonomi: 'Marknadsekonomi med låg skatt, begränsad omfördelning och stark tilltro till konkurrens och prismekanismer. Privatisering och avreglering ses som vägar till både effektivitet och ökad individuell handlingsfrihet. Inom forskningen används begreppet nyliberalism brett, vilket gör att det kan omfatta både en idétradition och olika reformprogram med delvis olika innehåll.',
    tänkare: ['Friedrich Hayek', 'Milton Friedman', 'James Buchanan', 'Ludwig von Mises'],
    spänningar: 'Spänning mellan marknadsfrihet och demokratisk legitimitet — avreglering, oberoende institutioner och global kapitalrörlighet kan minska nationalstatens handlingsutrymme. Dessutom finns en empirisk debatt om relationen mellan marknadsreformer, tillväxt, effektivitet och ojämlikhet: vissa menar att reformerna ökat välstånd, andra att de också förstärkt sociala klyftor på ett mer varaktigt sätt.',
    color: '#2f7b7b',
  },
  {
    id: 'ordoliberalism',
    label: 'Ordoliberalism',
    era: '1900-tal–',
    tagline: 'Marknadens frihet kräver statens starka hand.',
    core: [
      'Fri konkurrens skyddad av rättsliga institutioner',
      'Stark stat med begränsat mandat — regelsättare, inte spelare',
      'Monopol och karteller aktivt motverkade',
      'Prisstabilitet och sunda statsfinanser som grundvillkor',
    ],
    stateSyn: 'Staten ska skapa och upprätthålla ramverket för marknaden, men bör undvika att själv styra prisbildning eller produktion i detalj. Dess styrka mäts inte i hur mycket den gör, utan i hur konsekvent den upprätthåller konkurrensens spelregler och motstår särintressen som försöker kapa systemet.',
    ekonomi: 'Marknadsekonomi inom ett strikt institutionellt regelverk. Konkurrenslagstiftning prioriteras framför både laissez-faire och omfattande konjunkturstyrning. Sunda statsfinanser och prisstabilitet ses som centrala förutsättningar för att marknaden ska fungera utan att domineras av monopol, karteller eller politiskt gynnade grupper.',
    tänkare: ['Walter Eucken', 'Wilhelm Röpke', 'Ludwig Erhard'],
    spänningar: 'Spänning mellan regelbaserad återhållsamhet och behovet av aktiva institutioner — vem vaktar väktarna? Dessutom en spänning mot demokratin: om de ekonomiska spelreglerna görs mycket svåra att ändra, hur mycket utrymme finns då kvar för folkvalda att omforma samhällsekonomin?',
    color: '#5a6e9c',
  },
  {
    id: 'libertarianism',
    label: 'Libertarianism',
    era: '1900-tal–',
    tagline: 'Maximera frihet, minimera stat.',
    core: [
      'Icke-aggressionsprincipen',
      'Minimal eller ingen stat',
      'Starkt skydd för äganderätt',
      'Frivilliga associationer som samhällsgrund',
    ],
    stateSyn: 'Staten är ett nödvändigt ont i bästa fall — och i sin minimala form begränsad till att skydda individen mot våld, stöld och kontraktsbrott. Många libertarianer ifrågasätter statens legitimitet i grunden, men skiljer sig åt om huruvida en minimal nattväktarstat kan rättfärdigas.',
    ekonomi: 'Laissez-faire-kapitalism med stark äganderätt som grund. Skatter betraktas ofta som tvång snarare än som en normal medborgerlig skyldighet. Marknaden ses som det mest legitima systemet för resursallokering, eftersom frivilligt utbyte utan statlig inblandning anses vara både effektivt och moraliskt överlägset tvångsmässiga ordningar.',
    tänkare: ['Murray Rothbard', 'Robert Nozick', 'Ayn Rand'],
    spänningar: 'Spänning mellan den interna koherensen i icke-aggressionsprincipen och svårigheten att hantera kollektiva problem — exempelvis miljöskador, naturmonopol och fattigdom — utan gemensamma institutioner. Dessutom finns en intern spänning mellan minarkism och anarkokapitalism.',
    color: '#c9973a',
  },
  {
    id: 'ekologism',
    label: 'Ekologism',
    era: '1960-tal–',
    tagline: 'Naturens gränser som samhällets grundval.',
    core: [
      'Ekologisk hållbarhet och planetära gränser',
      'Decentralisering och lokalt självstyre',
      'Icke-antropocentrism — naturens egenvärde',
      'Intergenerationellt ansvar',
    ],
    stateSyn: 'Staten bör sätta ekologiska ramar som marknaden inte kan sätta själv och bidra till att ställa om samhällets strukturer inom dessa gränser. Eftersom miljöskador ofta externaliseras och naturresurser underprissätts krävs politisk styrning, även om olika ekologiska riktningar skiljer sig åt i synen på hur centraliserad denna styrning bör vara.',
    ekonomi: 'Ekonomin bör underordnas ekologiska gränser. Mått som hållbarhet, resiliens och långsiktig reproduktion av naturkapital ges högre vikt än enbart BNP-tillväxt. Vissa varianter av ekologism ifrågasätter ekonomisk tillväxt som centralt samhällsmål, medan andra söker förena marknadsekonomi med stark miljöstyrning och grön teknikutveckling.',
    tänkare: ['Arne Næss', 'Murray Bookchin', 'E.F. Schumacher'],
    spänningar: 'Spänning mellan ekologisk radikalism och den pragmatism som krävs för att nå politiskt genomslag. Dessutom finns en inre spänning om statens roll: ekologismen är ofta decentralistisk och misstänksam mot storskalig makt, men klimatomställningens omfattning tycks samtidigt kräva koordinering som bara starka institutioner kan leverera.',
    color: '#4a7a4a',
  },
  {
    id: 'socialism',
    label: 'Socialism',
    era: '1800-tal–',
    tagline: 'Kollektivt ägande av produktionsmedlen som väg till ekonomisk jämlikhet.',
    core: [
      'Kollektivt eller gemensamt ägande av produktionsmedlen',
      'Ekonomisk jämlikhet och avskaffande av klasskillnader',
      'Produktion för behov snarare än privat vinst',
      'Solidaritet och samarbete som samhällets organisationsprinciper',
    ],
    stateSyn: 'Socialismens syn på staten varierar med tradition. I demokratiskt socialistiska varianter betraktas demokratiska institutioner som ett legitimt verktyg för att omforma ägandeförhållanden och säkra ekonomiska rättigheter. Gemensamt för de flesta socialistiska strömningar är att den liberala statens neutralitet ifrågasätts: en stat som lämnar ägandet av produktionsmedlen i privata händer anses indirekt bevara rådande maktasymmetrier, oavsett vilka formella rättigheter som garanteras.',
    ekonomi: 'Det socialistiska ekonomiska programmet sträcker sig från begränsade reformer — utvidgad kooperativ sektor, stärkt löntagarinflytande, offentlig produktion inom nyckelområden — till mer genomgripande omvandlingar av ägandestrukturer. En gemensam nämnare är att produktionens inriktning inte enbart bör styras av privat vinstmotiv, utan underordnas bredare samhälleliga behov. Diskussionen om marknadsmekanismers roll inom en socialistisk ekonomi har pågått sedan 1800-talet och har givit upphov till bl.a. modeller för marknadssocialism och ekonomisk demokrati.',
    tänkare: ['Robert Owen', 'Henri de Saint-Simon', 'Rosa Luxemburg', 'G.D.H. Cole'],
    spänningar: 'Socialismen rymmer en ihållande intern debatt om vägen till förändring — parlamentarisk reform kontra mer genomgripande samhällsomvandling — och om det socialistiska samhällets ekonomiska organisation: hur mycket utrymme ska ges åt marknadsmekanismer, och hur kan ekonomisk demokrati förverkligas utan att leda till byråkratisk centralstyrning?',
    color: '#9f1239',
  },
];
